### ISSUE TITLE
Pokeradar

### ISSUE THREAD

**Issue by RandomUsernameOk** [kcaf/VirtualDMScreen#1]
Hello, I just wanted to ask, why would you stop the Pokeradar development ? You said it’s because “Pixelmon development stopped”, but Pixelmon Reforged is as official as it gets. I’m kinda new to GitHub so sorry if I’m wrong, but I can’t submit this issue on the Pokeradar page.

**Comment by kcaf** [comment]
I've posted the source code online. If you wish to continue the development of Pokeradar, you are more than welcome to do so. That is no longer a project I wish to continue and as the game falls under legality question, various versions will rise and fall and the code base will change significantly over increasingly shorter amounts of time. This leads to more upkeep as time progresses. I've removed the "Issue" posting for that project because the PokeRadar project is no longer being supported. Again, if you wish to take up the mantle yourself, you are more than welcome to download the original source code and continue development with my full permission. It is no longer my wish to continue that project at this time.
